import os 
import hashlib
import numpy as np 

configfile: "configs/config_umap.json"
configname = config["config_name"]

# Define function to generate seeds from wildcards given the combinations
def seed_from_wildcards(**wildcards):
    # Sort the wildcards to ensure stable ordering
    items = sorted(wildcards.items())
    # Create a consistent string representation
    rep = ",".join(f"{k}={v}" for k, v in items)
    
    # Hash the representation to get a big integer
    hash_val = int(hashlib.sha256(rep.encode("utf-8")).hexdigest(), 16)
    
    # Initialize a NumPy RNG with this hash as the seed
    # Since hash_val is deterministic for given wildcards, this RNG's output is too.
    rng = np.random.default_rng(hash_val)
    
    # Generate a stable integer seed (for example, in range [0, 2**31))
    seed = rng.integers(0, 2**31)
    return seed

# Get all combinations through the config file
def get_combinations(config, config_key):
    # Iterate over keys and values of config
    combinations = []
    for key, value in config[config_key].items():
        data_folder = value["data_folder"]
        ds_celltypes = value["ds_celltypes"]
        ds_proportions = value["ds_proportions"]
        num_batches = value["num_batches"]
        repetitions = value["repetitions"]
        if config_key == "int_ti_datasets":
            root_celltype = value["root_celltype"]
        # Get combinations of celltypes and proportions - sort by config_key (root celltype or not for TI)
        for num_batch in num_batches:
            for ds_celltype in ds_celltypes:
                for ds_proportion in ds_proportions:
                    for repetition in range(repetitions):
                        if config_key == "int_ti_datasets":
                            combinations.append(
                                "{data_folder}_root_{root_celltype}_{ds_celltype}_celltypes_{ds_proportion}_downsample_{num_batch}_batch_ds_c_{rep}".format(
                                    data_folder = data_folder,
                                    root_celltype = root_celltype,
                                    ds_celltype = ds_celltype, 
                                    ds_proportion = ds_proportion,
                                    num_batch = num_batch,
                                    rep = repetition
                                )
                            )
                        else:
                            combinations.append(
                                "{data_folder}_{ds_celltype}_celltypes_{ds_proportion}_downsample_{num_batch}_batch_ds_c_{rep}".format(
                                    data_folder = data_folder,
                                    ds_celltype = ds_celltype, 
                                    ds_proportion = ds_proportion,
                                    num_batch = num_batch,
                                    rep = repetition
                                )
                            )
    return combinations

# All rule - return summary results and intermediate integration h5ad files
if config["celltype_list"] == "No":
    if config["query_to_reference"] == "Yes":
        rule all:
            input:
                expand(
                    "../results/{configname}/{outputs[0]}/{dataset}_{outputs[1]}.{outputs[2]}",
                    configname = configname,
                    dataset = get_combinations(config, "int_ti_datasets"),
                    outputs = zip(
                        [
                            "paga_integrated_results",
                            "paga_imbalance_summaries",
                            "paga_ti_scores"
                        ], 
                        [
                            "paga_integrated",
                            "paga_imbalance_summary",
                            "paga_ti_score"
                        ],
                        [
                            "h5ad",
                            "tsv",
                            "tsv"
                        ]
                    )
                ),
                expand(
                    "../results/{configname}/{outputs[0]}/{dataset}_{outputs[1]}.{outputs[2]}",
                    configname = configname,
                    dataset = get_combinations(config, "int_datasets"),
                    outputs = zip(
                        [
                            "integrated_results",
                            "downsample_summaries", 
                            "clustering_summaries", 
                            "clustering_concord_summaries",
                            "dge_concord_full",
                            "dge_concord_stats",
                            "dge_ranking_stats",
                            "dge_ranking_results_per_cluster",
                            "dge_ranking_stats_marker_sub",
                            "imbalance_summaries",
                            "celltype_imbalance_summaries",
                            "knn_classification_reports",
                            "umap_plots",
                            "umap_plots",
                            "umap_plots"
                        ], 
                        [
                            "integrated",
                            "downsample_summary", 
                            "clustering_summary", 
                            "clustering_concord_summary",
                            "dge_concord_full",
                            "dge_concord_stats",
                            "dge_ranking_stats",
                            "dge_ranking_results_per_cluster",
                            "dge_ranking_stats_marker_sub",
                            "imbalance_summary",
                            "celltype_imbalance_summary",
                            "knn_classification",
                            "umap_leiden",
                            "umap_celltype",
                            "umap_batch"
                        ],
                        [
                            "h5ad",
                            "tsv", 
                            "tsv", 
                            "tsv", 
                            "tsv",
                            "tsv",
                            "tsv",
                            "tsv",
                            "tsv",
                            "tsv",
                            "tsv",
                            "tsv",
                            "pdf",
                            "pdf",
                            "pdf"
                        ]
                    )
                ),
                expand(
                    "../results/{configname}/marker_results/{dataset}_preintegration_marker_selection.tsv",
                        configname = configname,
                        dataset = [config["int_datasets"][key]["data_folder"] for key in config["int_datasets"].keys()]
                ),
                expand(
                    "../results/{configname}/relatedness_results/{dataset}_celltype_relatedness.tsv",
                        configname = configname,
                        dataset = [config["int_datasets"][key]["data_folder"] for key in config["int_datasets"].keys()]
                )
    else:
        if config["config_name"] == "pdac_comp_reanno":
           rule all:
                input:
                    expand(
                        "../results/{configname}/{outputs[0]}/{dataset}_{outputs[1]}.{outputs[2]}",
                        configname = configname,
                        dataset = get_combinations(config, "int_datasets"),
                        outputs = zip(
                            [
                                "integrated_results",
                                "downsample_summaries", 
                                "clustering_summaries", 
                                "clustering_concord_summaries",
                                "imbalance_summaries",
                                "celltype_imbalance_summaries",
                                "knn_classification_reports"
                            ], 
                            [
                                "integrated",
                                "downsample_summary", 
                                "clustering_summary", 
                                "clustering_concord_summary",
                                "imbalance_summary",
                                "celltype_imbalance_summary",
                                "knn_classification"
                            ],
                            [
                                "h5ad",
                                "tsv", 
                                "tsv", 
                                "tsv",
                                "tsv",
                                "tsv",
                                "tsv"
                            ]
                        )
                    ),
                    expand(
                        "../results/{configname}/relatedness_results/{dataset}_celltype_relatedness.tsv",
                            configname = configname,
                            dataset = [config["int_datasets"][key]["data_folder"] for key in config["int_datasets"].keys()]
                    )
        else:
            rule all:
                input:
                    expand(
                        "../results/{configname}/{outputs[0]}/{dataset}_{outputs[1]}.{outputs[2]}",
                        configname = configname,
                        dataset = get_combinations(config, "int_ti_datasets"),
                        outputs = zip(
                            [
                                "paga_integrated_results",
                                "paga_imbalance_summaries",
                                "paga_ti_scores"
                            ], 
                            [
                                "paga_integrated",
                                "paga_imbalance_summary",
                                "paga_ti_score"
                            ],
                            [
                                "h5ad",
                                "tsv",
                                "tsv"
                            ]
                        )
                    ),
                    expand(
                        "../results/{configname}/{outputs[0]}/{dataset}_{outputs[1]}.{outputs[2]}",
                        configname = configname,
                        dataset = get_combinations(config, "int_datasets"),
                        outputs = zip(
                            [
                                "integrated_results",
                                "downsample_summaries", 
                                "clustering_summaries", 
                                "clustering_concord_summaries",
                                "dge_concord_full",
                                "dge_concord_stats",
                                "dge_ranking_stats",
                                "dge_ranking_results_per_cluster",
                                "dge_ranking_stats_marker_sub",
                                "imbalance_summaries",
                                "celltype_imbalance_summaries",
                                "knn_classification_reports"
                            ], 
                            [
                                "integrated",
                                "downsample_summary", 
                                "clustering_summary", 
                                "clustering_concord_summary",
                                "dge_concord_full",
                                "dge_concord_stats",
                                "dge_ranking_stats",
                                "dge_ranking_results_per_cluster",
                                "dge_ranking_stats_marker_sub",
                                "imbalance_summary",
                                "celltype_imbalance_summary",
                                "knn_classification"
                            ],
                            [
                                "h5ad",
                                "tsv", 
                                "tsv", 
                                "tsv", 
                                "tsv",
                                "tsv",
                                "tsv",
                                "tsv",
                                "tsv",
                                "tsv",
                                "tsv",
                                "tsv"
                            ]
                        )
                    ),
                    expand(
                        "../results/{configname}/marker_results/{dataset}_preintegration_marker_selection.tsv",
                            configname = configname,
                            dataset = [config["int_datasets"][key]["data_folder"] for key in config["int_datasets"].keys()]
                    ),
                    expand(
                        "../results/{configname}/relatedness_results/{dataset}_celltype_relatedness.tsv",
                            configname = configname,
                            dataset = [config["int_datasets"][key]["data_folder"] for key in config["int_datasets"].keys()]
                    )
else:
    print("No")

# Integrate the indicated h5ad files from config, based on dataset, using the Universal Cell Embeddings foundation model
rule integrate_uce:
    conda:
        "envs/integrate_uce.yaml"
    input:
        "../resources/h5ad_files/int_datasets/{data_folder}"
    output:
        "../results/{configname}/integrated_results/{data_folder}_{ds_celltype}_celltypes_{ds_proportion}" +
        "_downsample_{num_batches}_batch_ds_c_{rep}_integrated_uce.h5ad"
    params:
        script_path = "scripts/python/integrate_data_UCE.py",
	seed = lambda wildcards: seed_from_wildcards(**wildcards)
    log:
        "logs/{configname}/integrate/integrate_{data_folder}_{ds_celltype}_celltypes_{ds_proportion}" +
        "_downsample_{num_batches}_batch_ds_c_{rep}_uce.log"
    priority: 0
    shell:
        """
        python {params.script_path} \
            --filedir {input} \
            --ds_celltypes {wildcards.ds_celltype} \
            --ds_proportions {wildcards.ds_proportion} \
            --num_batches {wildcards.num_batches} \
            --outfile {output} \
            &> {log}
        """